name: Secret Scanning

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  gitleaks:
    uses: redacted-org/.github/.github/workflows/gitleaks.yml@main
    permissions:
      contents: read
      security-events: write
      actions: read
