name: Secret Scanning

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  gitleaks:
    uses: redacted-org/.github/.github/workflows/gitleaks.yml@8c54bdaf3fb46d8bbabb228d2740c050dfe60986 # main
    permissions:
      contents: read
      security-events: write
      actions: read
